---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: {{ k8s_version }}
imageRepository: registry.aliyuncs.com/google_containers
networking:
  # This CIDR is a flannel default. Substitute or remove for your CNI provider.
  podSubnet: 10.244.0.0/16

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs