
#- name: 获取当前 kubeadm 版本
#  shell: "kubeadm config images list | head -1 | awk -F: '{ print $2 }'"
#  register: k8s_version

- name: 生成 kubeadm-config 配置文件
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: kubeadm_single-config.yaml ,dest: '/etc/kubernetes/kubeadm-config.yaml'}

- name: 初始化集群
  shell: "kubeadm init --config /etc/kubernetes/kubeadm-config.yaml"

- name: 拷贝 admin.conf 文件
  copy: src="/etc/kubernetes/admin.conf" dest="$HOME/.kube/config" remote_src=yes






