- name: install haproxy
  yum: name=haproxy state=installed

- name: 生成 haproxy 配置文件
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: haproxy.cfg.j2,dest: '/etc/haproxy/haproxy.cfg' }
    - {src: kubeadm-config.yaml.j2,dest: '/etc/kubernetes/kubeadm-config.yaml'}
- name: 启动 haproxy
  shell: systemctl enable haproxy && systemctl restart haproxy

#- name: 获取当前 kubeadm 版本
#  shell: "kubeadm config images list | head -1 | awk -F: '{ print $2 }'"
#  register: k8s_version

- name: 初始化集群
  shell: "kubeadm init --config /etc/kubernetes/kubeadm-config.yaml"

- name: 拷贝 admin.conf 文件
  copy: src="/etc/kubernetes/admin.conf" dest="$HOME/.kube/config" remote_src=yes
  ignore_errors: True






